version: "3.8"

services:
  frontend:
    container_name: frontend
    restart: always
    volumes:
      - /app/node_modules
      - ./src:/app/src
    build: .
    environment:
      FAST_REFRESH: 0
      WATCHPACK_POLLING: 1
    ports:
      - "3000:3000"
    command: npm start
